name: Test MTA works on various platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-mta-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/rhappsvcs/spring-to-quarkus-mta-cli:latest

      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh

  # verify-mta-macos-10-podman:
  #   runs-on: macos-10.15
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Install podman
  #       run: .github/workflows/scripts/install-podman-macos.sh
  #     - name: Run MTA
  #       run: podman run -v $GITHUB_WORKSPACE:/opt/project:z,U quay.io/edeandrea/mta-cli:latest
  #     - name: Assert MTA output
  #       run: .github/workflows/scripts/assertMta.sh

  # verify-mta-macos-11-podman:
  #   runs-on: macos-11
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Install podman
  #       run: .github/workflows/scripts/install-podman-macos.sh
  #     - name: Run MTA
  #       run: podman run -v $GITHUB_WORKSPACE:/opt/project:z,U quay.io/edeandrea/mta-cli:latest
  #     - name: Assert MTA output
  #       run: .github/workflows/scripts/assertMta.sh

  # verify-mta-macos-10:
  #   runs-on: macos-10.15
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Install docker
  #       run: .github/workflows/scripts/install-docker-macos.sh
  #     - name: Run MTA
  #       run: |
  #         eval $(docker-machine env mta)
  #         docker run -v $(pwd):/opt/project -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
  #     - name: Assert MTA output
  #       run: .github/workflows/scripts/assertMta.sh

  # verify-mta-macos-11:
  #   runs-on: macos-11
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Install docker
  #       run: .github/workflows/scripts/install-docker-macos.sh
  #     - name: Run MTA
  #       run: |
  #         eval $(docker-machine env mta)
  #         docker run -v $(pwd):/opt/project -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
  #     - name: Assert MTA output
  #       run: .github/workflows/scripts/assertMta.sh

  # verify-mta-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2
  #     - name: Switch to linux container
  #       run: "& $Env:ProgramFiles\\Docker\\Docker\\DockerCli.exe -SwitchDaemon"
  #     - name: Run MTA
  #       run: docker run -v %cd%:/opt/project quay.io/edeandrea/mta-cli:latest
  #     - name: Assert MTA output
  #       run: .github/workflows/scripts/assertMta.bat
